---
title: "Term Paper Proposals"
author: "Boyu, Chen R11323006"
date: "2023-03-30"
output: beamer_presentation
---

## Idea 1: Examine the change in the working hours gap between commuters and remote workers before and after the pandemic outbreak.

In my intuition, white-collar workers are more likely to WFH during the pandemic. If people are beneficial form WFH, then there is no need to live in the city. And it can also save the time cost of commuting.

should I use panel data?

## Idea1: Identification Strategy
-   DATA: SRDA Manpower Utilization Survey
-   Y: working hours
-   Xs: age, wage, educ, work_year, occupation, # of children, marital status
-   D: WFH_or_not (during pandemic)
-   group by
    -   treatment group: commuters (before) -\> remote workers (after)
    -   control group: commuters (before) -\> commuters (after)
-   method: DID (maybe)

## Idea 2: The change of time use on sports before and after the pandemic.

During the pandemic, people have started to pay more attention to their health. I am interested in the idea that if "people who started work from home have the same salary, shorter working hours, and more time to exercise than before", then we can expect people to become healthier. Under this statement, companies and governments should encourage people to work from home.


## Idea2: Identification Strategy
-   DATA: IPUMS time use data
-   Y: sports_time
-   Xs: age, wage, educ, work_year, occupation, # of children, marital status
-   D: WFH_or_not
-   group by
    -   either "High income vs. low income"
    -   or "High educ vs. low educ"
-   method: DID (maybe)
